name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install torch==2.5.1 --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest --cov=slt --cov-report=term-missing
