name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install torch==2.5.1 --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements-dev.txt
      - name: Ruff lint
        run: ruff check .
      - name: Black formatting check
        run: black --check .
      - name: Type checking
        run: mypy .
      - name: Run tests
        run: pytest --cov=slt --cov-report=term-missing
      - name: Export smoke test
        run: python -m pytest tests/test_export.py::test_main_export_generates_onnx_and_torchscript
      - name: Validate data contract fixtures
        run: python tools/ci_validate_data_contract.py
      - name: Validate README reference metrics
        run: python tools/ci_validate_metrics.py
